import Head from "next/head";
import { getClient } from "../lib/sanity-server";
import groq from "groq";

export default function Home({ posts }) {
  console.log(posts);
  return (
    <div>
      <Head>
        <title>Pack Your Bags</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
}

export async function getStaticProps({ preview = false }) {
  const posts = await getClient(preview).fetch(groq`
  *[_type == 'post' && publishedAt < now()] | order(publishedAt desc) {
  _id,
  title,
  "username": author->username,
  "categories": categories[]->{id, title},
  "authorImage": author->avatar,
  body,
  mainImage,
  slug,
  publishedAt,
}
  `);

  return {
    props: {
      posts,
    },
  };
}
